import { CapabilityItem, ImpactMetric, ReentryPhase } from '../types';

export const REENTRY_PHASES: ReentryPhase[] = [
  {
    id: 'phase-1',
    number: '01',
    title: 'In-Facility Readiness & Skills Bootcamp',
    subtitle: 'Pre-Release Preparation (6 Months Prior to Release)',
    description: 'Delivers high-impact vocational training, financial literacy, cognitive-behavioral programming, and personalized digital portfolios inside correctional facilities.',
    outcomes: [
      'Certified Digital Literacy & OSHA/Vocational Credentials',
      'Individualized Reentry Action Plan (IRAP)',
      'Pre-approved State ID & Vital Documentation Processing'
    ],
    metrics: [
      { label: 'Completion Rate', value: '94.2%' },
      { label: 'Certifications Earned', value: '1,840+' }
    ],
    status: 'In-Facility'
  },
  {
    id: 'phase-2',
    number: '02',
    title: 'The Warm Handoff & First 72 Hours',
    subtitle: 'Immediate Stabilization & Transportation Support',
    description: 'Dedicated Peer Support Specialists coordinate direct transportation from release point to safe housing, immediate healthcare intake, and phone/digital connectivity.',
    outcomes: [
      'Zero 72-Hour Homelessness Rate for Program Graduates',
      'Immediate Food, Clothing & Transit Pass Allocation',
      'Same-Day Peer Mentorship Assignment'
    ],
    metrics: [
      { label: '72-Hr Stabilization', value: '98.6%' },
      { label: 'Avg Intake Time', value: '< 2 Hours' }
    ],
    status: 'Warm Handoff'
  },
  {
    id: 'phase-3',
    number: '03',
    title: 'Workforce Placement & Employer Bridge',
    subtitle: 'Career Trajectory (Days 4 - 90)',
    description: 'Direct matching with vetted employer partners offering livable-wage positions, work transportation stipends, and ongoing workplace retention coaching.',
    outcomes: [
      'Over 85 Direct Hiring Partner Corporations',
      'Average Starting Wage of $21.50/hr',
      'Employer Tax Incentive (WOTC) Support Assistance'
    ],
    metrics: [
      { label: '90-Day Job Retention', value: '88.4%' },
      { label: 'Avg Wage Growth', value: '+18% at 6 mo' }
    ],
    status: 'Career Launch'
  },
  {
    id: 'phase-4',
    number: '04',
    title: 'Sustained Thriving & Community Integration',
    subtitle: 'Long-Term Independence (Months 3 - 36)',
    description: 'Ongoing peer support circles, housing transition assistance, leadership development, and credit-building mentorship for permanent self-sufficiency.',
    outcomes: [
      '3-Year Recidivism Rate Reduced to 14.2% (vs 43.8% State Avg)',
      'Savings of $42,000+ per Incarceration Year Avoided per Taxpayer',
      'Alumni Leadership Network & Peer Mentorship Pipeline'
    ],
    metrics: [
      { label: '3-Year Success Rate', value: '85.8%' },
      { label: 'Taxpayer ROI', value: '4.8x' }
    ],
    status: 'Sustained Thriving'
  }
];

export const IMPACT_METRICS: ImpactMetric[] = [
  {
    category: '3-Year Recidivism Rate',
    baseline: 43.8,
    acsProgram: 14.2,
    unit: '%',
    description: 'Significantly lower re-arrest and re-incarceration rate measured over a 36-month tracking window.'
  },
  {
    category: '90-Day Employment Retention',
    baseline: 42.0,
    acsProgram: 88.4,
    unit: '%',
    description: 'Sustained job placement with career advancement pathways in logistics, tech, and trades.'
  },
  {
    category: 'Annual Taxpayer Savings Per Participant',
    baseline: 0,
    acsProgram: 42500,
    unit: 'USD',
    description: 'Direct savings generated by avoiding incarceration costs and increasing state income tax contributions.'
  },
  {
    category: 'Stable Permanent Housing Rate',
    baseline: 38.5,
    acsProgram: 91.2,
    unit: '%',
    description: 'Participants securing independent lease agreements or stable home placements within 6 months.'
  }
];

export const CAPABILITIES_DATA: CapabilityItem[] = [
  {
    code: 'NAICS 541810',
    title: 'Advertising & Strategic Communication Agencies',
    category: 'Creative & Strategy',
    description: 'Comprehensive public awareness campaigns, agency rebranding, and strategic messaging for government programs.',
    deliverables: ['Multi-Channel Media Strategy', 'Public Service Announcements (PSAs)', 'Targeted Stakeholder Outreach']
  },
  {
    code: 'NAICS 541511',
    title: 'Custom Computer Programming Services',
    category: 'Digital & Software',
    description: 'Development of web platforms, participant portals, data tracking analytics dashboards, and interactive learning tools.',
    deliverables: ['Custom Participant Portals', 'Data Analytics Dashboards', 'Secure Cloud Architecture']
  },
  {
    code: 'NAICS 541611',
    title: 'Administrative Management & General Consulting',
    category: 'Program Management',
    description: 'Turnkey operational planning, recidivism reduction framework implementation, and inter-agency collaboration modeling.',
    deliverables: ['Program Execution Blueprints', 'Performance Metric Frameworks', 'Grant & RFP Compliance Reports']
  },
  {
    code: 'NAICS 512110',
    title: 'Motion Picture & Video Production',
    category: 'Media Production',
    description: 'High-definition promotional, educational, and training video production with custom AI scripts and voiceovers.',
    deliverables: ['4K Promotional Videos', 'Training & Orientation Modules', 'Impact Story Documentaries']
  }
];
